DROP TABLE IF EXISTS PUBLIC.FACT_MONTHLY_AIR_DATA;
CREATE TABLE PUBLIC.FACT_MONTHLY_AIR_DATA AS(
  SELECT
    "the_date",
    hours_utc,
    "FAFFD",
    "FALIF",
    "FALJI",
    "FAMXK",
    "FAYJG",
    "FAZKI",
    "FBKKK",
    "FBLJL",
    "FBLKS",
    "FCAEN",
    "FCCOT",
    "FCFUU",
    "FCGKZ",
    "FCIBD",
    "FCKTB",
    "FCNJT",
    "FCTOV",
    "FCWFX",
    "FCWOV",
    "FCWYG",
    "FDATE",
    "FDCHU",
    "FDEGT",
    "FDGED",
    "FDGEJ",
    "FDGEM",
    "FDJFN",
    "FDMOP",
    "FDQBU",
    "FDQBX",
    "FDSUS",
    "FDZCP",
    "FEAKO",
    "FEARV",
    "FEBWC",
    "FEUTC",
    "FEUZB",
    "FEVJR",
    "FEVJS",
    "FEVJV",
    "FEVNS",
    "FEVNT",
    download_link,
    src_filename,
    last_updated,
    NOW() AT TIME ZONE 'EST' AS last_inserted
  FROM(
      SELECT *
   , ROW_NUMBER() OVER(PARTITION BY "the_date","hours_utc" ORDER BY hours_utc DESC) AS RN
      FROM STAGE.stg_monthly_air_data
  ) A WHERE RN=1);